### ISSUE TITLE
Select Route

### ISSUE THREAD

**Issue by VACoder** [Code4HR/hrt-bus-finder#1]
I'm on a Windows Lumia 920 Phone running Windows Phone 8.0. I entered Jefferson and Harpersville Road as the intersection in Newport News. I clicked on Select Route. The 'Inbound' and 'Outbound' links were not functional.

**Comment by bschoenfeld** [comment]
This bug should have been opened in c4hrva/hrt-bus-api. Confusing, I know.

**Comment by bschoenfeld** [comment]
Fixed in bschoenfeld/hrt-bus-api@db1a83c54c11435b8ac2b39b64b998f7bf4c9c5c

**Comment by VACoder** [comment]
D'oh. Maybe I can get a github 101 from someone at the next meetup I can
make!

Thanks.

Richard Ruth

MCTS SharePoint ® 2010, Application Development

MCTS SharePoint ® 2010, Configuration

CompTIA Security+

**Comment by bschoenfeld** [comment]
No, you did nothing wrong. We have at least 3 different bus app repos at
this point. It causes a lot of confusion. I'm working on fixing that.
Thanks for the bug report. I should have automated tests to catch stuff
like this.
