### ISSUE TITLE
Improve UI of Disclaimer Modal

### ISSUE THREAD

**Issue by wbprice** [Code4HR/hrt-bus-finder#115]
Disclaimer modal breaks app on smaller screens.  User can't close window and get to app. Replace with disclaimer that slides beneath header and says something like:

Use of the HRT Bus Finder signifies that you have read and accepted the [terms and conditions](link).

Which disappears after 10 seconds.

**Comment by BretFisher** [comment]
this feature request from users has 3 votes on uservoice. https://hrtbus.uservoice.com/forums/217073-general/suggestions/5854029-please-remove-the-floating-popup-disclaimer

**Comment by wbprice** [comment]
This is probably not going to happen before Saturday. I'll see about addressing during NDoCH.

**Comment by wbprice** [comment]
This was fixed already.
