### ISSUE TITLE
Color code minutes to arrival and adherence info

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#12]
Minutes to arrival should have different colors for values representing yet to arrive, arriving now, and already left.

Adherence info should have different colors for values representing, late, on time, and early.

**Comment by bschoenfeld** [comment]
Right now, the minutes to arrival boxes have a red background and white text. The route number boxes have light blue background and dark blue text. I think we should change the minutes to arrival boxes to have the same blue background as the route number boxes. I think it will balance the page and won't draw so much negative attention to the minutes to arrival.

Then I think the text color in the minutes to arrival box should change depending on the time. Greater than 10 minutes and up should be green, 3-9 should be yellow, and less than 3 (including 'Now' and 'Gone') should be red.

**Comment by wbprice** [comment]
Do we still want to change colors of minutes to arrival boxes or are we happy with the way it is now (blue for time to arrival > 5 mins and red for time to arrival < 5)?

**Comment by BittenBagel** [comment]
Color scheme I created for the bus time's. Left to right. Left being "you have plenty of time", while moving to the right being "you are running out of time". 

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::hex codes from left to right:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

.............#84BA71........................... #E0CC47............................#E89F31............................#DB5051..........
.........20 min away.........................15 min away.........................10 min away....................5 min away.........

![screen shot 2015-05-20 at 8 16 21 pm](https://cloud.githubusercontent.com/assets/11762323/7739339/18ed4362-ff2d-11e4-8e1a-d3005edc98bc.png)

**Comment by wbprice** [comment]
@BittenBagel The logic for changing the time to arrival background color in the JavaScript is here: https://github.com/Code4HR/hrt-bus-finder/blob/gh-pages/js/busfinder.js#L414

Setup additional classes in the CSS here:
https://github.com/Code4HR/hrt-bus-finder/blob/gh-pages/css/busfinder.css#L260

If you have any questions about how to proceed let me know.

**Comment by BittenBagel** [comment]
Thank you so much!

**Comment by wbprice** [comment]
Addressed in #161
