### ISSUE TITLE
Bus app is down

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#121]
Time 4:30PM 12/4/2014

RE: 
Hey guys,  the busses aren't rolling.  One or two blue icons on the map but nothing's rolling. 

Brett

cc @bschoenfeld

**Comment by qwo** [comment]
I checked the FTP feed and it looks like its OK and im now checking the API. 

It looks to me the times are updating correctly but im not standing physical at a stop to verify

**Comment by qwo** [comment]
example > feed and times are updating but the positions aren't. what explains that?

EDIT: The last check event time all buses checked in was:  busCheckinTime: "2014-12-04T13:13:12". 
EDIT2: Location of Bus 1241 as of 545 minutes ago.
http://api.hrtb.us/api/stop_times/0272/

**Comment by qwo** [comment]
Leading theory for me, change in schedule? the feed looks right, the api serves correctly. is this behavior for when the schedule gets changed on the feed?

**Comment by bschoenfeld** [comment]
Process FTP script is getting this error

```
Traceback (most recent call last):
  File "process-ftp.py", line 90, in <module>
    ftp = FTP('216.54.15.3')
  File "/usr/lib/python2.7/ftplib.py", line 117, in __init__
    self.connect(host)
  File "/usr/lib/python2.7/ftplib.py", line 135, in connect
    self.welcome = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 217, in getresp
    raise error_temp, resp
ftplib.error_temp: 421
```

**Comment by qwo** [comment]
I haven't been able to trace this down. is it recommended to disable or warn users about app being broken?

I mentioned this to @ttavenner and it looked like it was working to him as did I. Should an error page be subsituted while its down? don't want anyone trying to use this right now. 

cc @kmcurry @BretFisher

**Comment by qwo** [comment]
RE:
looks like the ftp feed is down. ftp://216.54.15.3
ftp://216.54.15.3/Anrd/hrtrtf.txt
https://github.com/Code4HR/hrt-bus-api/blob/master/scripts/process-ftp/process-ftp.py#L91

**Comment by bschoenfeld** [comment]
The best solution is to throw out data that is older than 10 minutes or so because its not valid anymore. The home page is still good because it uses schedule data, not real time.

**Comment by bschoenfeld** [comment]
I'm not able to connect to the server on my box using Python. We probably need to ask HRT to look into it.

**Comment by BretFisher** [comment]
Any update?

**Comment by bschoenfeld** [comment]
Kamlesh,

We've been getting some errors trying to connect to the FTP site for the
last few days. Error 421 is what I'm seeing. If you have some time, could
you take a look of us?

Thanks,
Ben

**Comment by bschoenfeld** [comment]
Emailed HRT IT just now

 Kamlesh Chowdhary kchowdhary@hrtransit.org
 Alesia Cain acain@hrtransit.org

**Comment by wbprice** [comment]
I'll add a message today that explains what's going on to users.

**Comment by bschoenfeld** [comment]
Just got an email from HRT that they corrected the problem. Looks like it's working now.
