### ISSUE TITLE
Invalid Email @c4hrva-team

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#122]
During rebranding we change it to @code4hr  

c4hrva-team@codeforamerica.org is a deleted email. https://github.com/Code4HR/hrt-bus-finder/blob/gh-pages/index.html#L198

**Comment by qwo** [comment]
i discovered this when someone recently filed a bug report that the bus app is experiencing difficulty.

**Comment by BretFisher** [comment]
Fixed with 04fd7b958bec31da16e83f943f80b11e2df089bf

**Comment by qwo** [comment]
:+1: thanks!
