### ISSUE TITLE
the close button on the top right of the popover is transparent, when it should actually be visible

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#125]
The close on the map is transparent, it is hard to know how to close the popovers

**Comment by qwo** [comment]
![screenshot 2015-02-21 15 30 32](https://cloud.githubusercontent.com/assets/3683993/6315882/bc1591b4-b9de-11e4-8c4e-5a9705fb916c.png)

**Comment by mark4carter** [comment]
It looks like these are fine now on my desktop and on s4 phone.

**Comment by qwo** [comment]
@mark4carter sorry ill update the description. There is a close button in the top right corner of each popover. its transparent so its hard for the user to know they can close the popovers.

I naturally always click it there but otherwise the popover will hover. This came from a user testing session with one of HRT's social managers, they mentioned you couldn't close the popovers but it was because the button is transparent

The title is "the close button on the top right of the popover is transparent, when it should actually be visible "

**Comment by mark4carter** [comment]
![image](https://cloud.githubusercontent.com/assets/6766137/10413405/bff647a4-6f75-11e5-8cd5-f0ef72bf0f0f.png)
Its working on chrome

**Comment by qwo** [comment]
looks good to me. must of been fixed on some iteration and never closed. Awesome
