### ISSUE TITLE
Add the basics to the README

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#14]
The README is empty! It should have a screen shot and tell everyone how easy it is to work on this project. Just open index.html in your browser!

**Comment by qwo** [comment]
https://github.com/c4hrva/hrt-bus-finder/pull/49

**Comment by qwo** [comment]
Misread the issue but adjusted it. Let me know if it needs more changes

**Comment by bschoenfeld** [comment]
Done in #58. @stanzheng, feel free to add your stuff in. I used this one since it was one concise commit.
