### ISSUE TITLE
Improve Design of Sidebar

### ISSUE THREAD

**Issue by wbprice** [Code4HR/hrt-bus-finder#148]
![screen shot 2015-05-20 at 7 58 05 pm](https://cloud.githubusercontent.com/assets/2590422/7739147/9ba6af9e-ff2a-11e4-9d99-880e7fe3d72b.png)

Things that could be better about the sidebar
- Darken the main body as it is pushed to the left, giving more focus to the sidebar
- Adjust the color scheme so the sidebar doesn't seem connected to stop cards
- Your suggestions here

**Comment by wbprice** [comment]
Alternatively: http://codepen.io/wbprice/details/EjgpBq/

**Comment by pchinjr** [comment]
Is anyone working on this? I'd like to take it on. -thanks!

**Comment by wbprice** [comment]
Yes please!

**Comment by wbprice** [comment]
Resolved in #177
