### ISSUE TITLE
Synchronize styles between header and rest of app.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/hrt-bus-finder#17]
I'd like to stick with flat design for the app, so I'm going to work on the header styles to bring them in line with everything else.

**Comment by bschoenfeld** [comment]
The app just uses bootstrap's default right now... I wonder what bootstrap is going to do now that the whole world (read Apple) is going flat.

**Comment by wbprice** [comment]
I've got the header styles ready to go except for the logo.  Working on getting an image editor on my netbook.

**Comment by bschoenfeld** [comment]
Do what you will with the logo. I just pulled this one off the HRT site and modified it slightly... http://www.gohrt.com/wp-content/themes/hrtransit/images/content/logo.png

**Comment by bschoenfeld** [comment]
Here's another one. I think its a bit ugly and low res... maybe we can find a higher res version if you want to work off of it - http://www.gohrt.com/wp-content/uploads/2013/05/HRT-stacked.png

**Comment by wbprice** [comment]
Kevin mentioned at one point that HRT wanted us to use a specific logo.  I'll stick with what I have for now, sounds like it could change in the near future.

**Comment by bschoenfeld** [comment]
Fixed by #21
