### ISSUE TITLE
Zapier Uservoice/Github Issues

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#178]
@BretFisher might give us a high profile when suggestions show up 

Theres a zap but i dont have the credentiails AFAIK to uservoice, do you mind enabling this? 

if not i can turn it on

https://zapier.com/app/min/5114/start

**Comment by BretFisher** [comment]
We want to track issues not suggestions IMO, but I'll signup for both. and also have it notify slack (or do we have GHIssues already posting to slack?)

**Comment by BretFisher** [comment]
done

**Comment by qwo** [comment]
awesome thanks!

a lot of the user voice questions i haven't seen before, we should at least
make them into issues/slack pushes so we remember it lives somewhere and
make sure to have someone address them or close them as needed

On Thu, Feb 18, 2016 at 10:57 PM, Bret Fisher notifications@github.com
wrote:

> done
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Code4HR/hrt-bus-finder/issues/178#issuecomment-186041065
> .

## 

Stanley Zheng
