### ISSUE TITLE
New Uservoice Suggestion: Change the destination for Downtown Norfolk buses 

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/hrt-bus-finder#180]
This app still has Wood and Church for the destination of Downtown Norfolk buses. It needs to be updated to have the new transportation center.

http://hrtbus.uservoice.com/forums/217073-general/suggestions/12245997-change-the-destination-for-downtown-norfolk-buses
##

**Comment by DaveHarrisVA** [comment]
I believe this is a function of the Google Transit feed provided by HRT that only they can change.  The contact person at HRT is listed at some point a few months ago in #hrtbus on slack.  I had success convincing him to change something else mildly related to this ticket on the Google Transit feed, so I'm sure he will be helpful here.

Edit: Unless, of course, this is somehow hard coded into HRTBUS too...
