### ISSUE TITLE
New Years Bug

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#196]
The backend has trouble handling year changes. It has to figure out which year each checkin from HRT is in since HRT only includes the month, day, and time. There are some boundary case issues that cause the code to create checkins in the wrong year (usually one year ahead) and these checkins get stuck in the database and break the app.

**Comment by qwo** [comment]
@bschoenfeld I think you closed this with https://github.com/Code4HR/hrt-bus-api/commit/b66a10e5942ea5319ac966e9128d6ccd7a94dc2a

**Comment by bschoenfeld** [comment]
Yes. Good catch.

**Comment by bschoenfeld** [comment]
The actual commit is https://github.com/Code4HR/hrt-bus-api/commit/32fe813868f83a21edd32bc77b10bd5d9e944d1a
