### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#23]
Create favicon and [iOS Webclip Icon](http://developer.apple.com/library/ios/#documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW4) as suggested by [@FixHRT](https://twitter.com/FixHRT/status/312675035812884481)

**Comment by qwo** [comment]
@cosmicmeow

**Comment by wbprice** [comment]
I threw together something that's consistent with the rest of the design.  #73
