### ISSUE TITLE
Make and publish an About

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/hrt-bus-finder#27]
- [x] By Code for Hampton Roads (link)
- [ ] Contact email (link), Use Twitter hashtag #c4hrva (link) for help
- [ ] Simplest Disclaimers as required and advised
- [ ]  Be Kind.

**Comment by kmcurry** [comment]
Add link to About from list and map view

**Comment by wbprice** [comment]
I'll knock this out early tomorrow afternoon.  Do we have an info@codeforhamptonroads.org address we can use?

**Comment by wbprice** [comment]
Here's the language I'm including in pull request #26. [links] where appropriate.

HRT Bus Finder was developed by volunteers from [Code for Hampton Roads] in cooperation with [Hampton Roads Transit].

For help using this app or to answer any questions, send us an [email]\* or tweet [@oilytheotter] or [@wbprice] with hashtag #c4hrva.

We've worked hard to make the data delivered by HRT Bus Finder as accurate as possible, but we cannot be held responsible for any innaccurate information.

*I'm using the non-existent email address bus-tracker@codeforhamptonroads.org right now.

**Comment by BretFisher** [comment]
how about you give them our new support link http://hrtbus.uservoice.com and change the About link to Help.

**Comment by BretFisher** [comment]
Twitter hashtag is great but many won't do that, and uservoice is a great support framework. I've been thinking for a while how we will scale our support and ops of "all these apps". We should discuss the issues at a hacknight.

**Comment by kmcurry** [comment]
I also recommend not using personal contact info. Use a group account.
Uservoice prob covers that.

On Thursday, August 1, 2013, Bret Fisher wrote:

> how about you give them our new support link http://hrtbus.uservoice.comand change the About link to Help.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/hrt-bus-finder/issues/27#issuecomment-21983534
> .

## 

Kevin Curry
Program Director
CfA Brigade
757.613.8158
GMT-4 (EDT)
http://brigade.codeforamerica.org

_Apply for Fellowship: http://codeforamerica.org/apply_

**Comment by bschoenfeld** [comment]
Here's what's live:

HRT Bus Finder was developed by volunteers from [Code for Hampton Roads](http://codeforhamptonroads.org/) in cooperation with [Hampton Roads Transit](http://gohrt.com/).
For help using this app or to answer any questions, contact us using [Uservoice](http://hrtbus.uservoice.com/).
We've worked hard to make the data delivered by HRT Bus Finder as accurate as possible, but we can't be held responsible for any innaccurate information.

Closed by #28
