### ISSUE TITLE
Differentiate light rail and ferry stops

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#45]
These show up in the app, even though there is no real time information. I don't want to take them out, because the information is perfectly valid, but the app should mention that they are different. The API will need to have this information added.

**Comment by wbprice** [comment]
On the front end side, after we've decided how we'll differentiate between light rail/ferry stops and bus stops, we could just put an icon in the background of a train or boat.  No need to have a bus icon for every stop.  Noun project has a couple of solid free icons we can use.

**Comment by bschoenfeld** [comment]
Turning this over to you @wbprice. Each div with schedule class will also have a class that represents the type of route the arrival is: 'light-rail-route', 'bus-route', or 'ferry-route'.

**Comment by wbprice** [comment]
I'm thinking that we'll add an icon for ferry and light-rail stops, but not bus stops to the background of .schedule.  added in #73
