### ISSUE TITLE
Cannot return after viewing Route Selection 

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#50]
the new bus route viewer _**top right button *_\* pulls up a scrollable selection view of all routes in Hampton Roads at the moment.

Attempting to return to the Bus App is not possible unless app is reloaded, and it gets 'stuck' in this view.

tested Safari iOS iphone5

**Comment by bschoenfeld** [comment]
Unable to reproduce. Can you provide exact steps?

**Comment by qwo** [comment]
Was earlier, just tried it again and it works normal behavior.

Maybe it was my phone or my own error.

Thanks Ben
