### ISSUE TITLE
Too much information for the interface?

### ISSUE THREAD

**Issue by wbprice** [Code4HR/hrt-bus-finder#56]
The mobile view is getting too cluttered.  We should look at paring back some of the information that isn't relevant/confusing to the average user.  I'd like to move the time of arrival and adherence data.  This could go down to the same place as the Bus ID and time of last update.  The trend we're on is to put information for power users below the map.

**Comment by bschoenfeld** [comment]
Sounds good to me

**Comment by wbprice** [comment]
Addressed in #57.

**Comment by bschoenfeld** [comment]
Closed by #57
