### ISSUE TITLE
Deprecate old bus finder

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#66]
The old bus finder is still live at map.hrtb.us. According to Google Analytics, we still get a ton of hits on that page. Some of the hits are direct links to certain routes. We need to put an annoying banner on that site that warns the user that the site will be taken down soon and offers to redirect them to the appropriate part of the new site.

**Comment by bschoenfeld** [comment]
Example: http://map.hrtb.us/busfinder/routes/1/ should redirect to http://hrtb.us/#/routes/1/

**Comment by qwo** [comment]
closed?
