### ISSUE TITLE
Add Disclaimer

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#67]
HRT has asked that we show the user a disclaimer before they use the bus app. It should pop up when the app is loaded and the user should have to press OK to dismiss the message. Preferably, the message won't be shown to the user if they have already seen it on a previous visit to the app.

This is [HRT's official disclaimer](ftp://216.54.15.3/Anrd/Real%20Time%20Data%20Disclaimer.pdf) that they have posted along side the real time data feed. We can tweak it (e.g. remove the reference to the file), but this is probably the language we should go with:

Disclaimer 

Hampton Roads Transit (HRT) is providing the real time data contained in “hrtrtf.txt” file on an experimental basis. HRT cannot be held responsible for the accuracy of this data. Any applications using this data are not made by HRT, and HRT does not sell or license the apps. They are written by third parties unless otherwise noted. HRT shall not be held responsible for the content of third party websites or any issue arising from the use of third party applications. HRT neither endorses any third party products that use this data nor makes any guarantees or representations as to accuracy or reliability. Proceed with care and understand any usage charges that may apply to you. HRT reserves the right to remove/modify this real time data listing without notice.

**Comment by wbprice** [comment]
This is being addressed in #73.
