### ISSUE TITLE
Browser Testing 

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#72]
Android 4.1 - Dolphin Stock Browser 
Bus information is overlapping the Stops.

*\* uploading screenshot soon**

**Comment by qwo** [comment]
http://imgur.com/P1sAcfd

**Comment by wbprice** [comment]
Is this still happening?  I haven't been able to get the site to load on my phone all day for whatever reason or I'd check myself.

**Comment by qwo** [comment]
Clear cache? 

Ben said that if there was high load it would  take over 15 seconds to load.

Crud apps not loading for me on mobile.

**Comment by wbprice** [comment]
It works pretty consistently on desktop, so I'm not sure what's going on with mobile at the moment.

**Comment by qwo** [comment]
I would double check tomorrow with michelle, that was where the problem was
noted.

It was an android phone running stock browser on 4.1 Jellybean.

As for the mobile issues, I think that has to do with the APP making
requests everytime its open.

@bschoenfeld do you think we need to introduce a datastore or something as
a middleman?

On Tue, Oct 29, 2013 at 10:19 PM, William Blaine Price <
notifications@github.com> wrote:

> It works pretty consistently on desktop, so I'm not sure what's going on
> with mobile at the moment.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/hrt-bus-finder/issues/72#issuecomment-27360537
> .
> 
> ---
> 
> NOTE: This message was trained as non-spam. If this is wrong, please
> correct the training as soon as possible.
> Spamhttps://www.spamtrap.odu.edu/canit/b.php?i=02KHejM6A&m=79bf0a57eb9f&t=20131029&c=s
> Not spamhttps://www.spamtrap.odu.edu/canit/b.php?i=02KHejM6A&m=79bf0a57eb9f&t=20131029&c=n
> Forget previous votehttps://www.spamtrap.odu.edu/canit/b.php?i=02KHejM6A&m=79bf0a57eb9f&t=20131029&c=f

## 

Stanley Zheng
B.S. Computer Science Major
Old Dominion University 2014
Cell: (347)-399-3732

**Comment by bschoenfeld** [comment]
I notice issues loading the app on mobile less than 5% of the time. I don't
think it has anything to do with the app refreshing data. It's just making
Ajax requests and getting json data back. How would your suggestion work?
When buses checkin, the server gets that data and the only way for the app
to show it is to ask the server. Buses checkin every minute.

If there are issues loading the app, please let me know more about it. If
the page doesn't load correctly or looks strange, that's a problem with the
github hosting. Maybe we need to look into fixing that and making sure all
the js and CSS is minified.

**Comment by BretFisher** [comment]
IE has issues. Figured we should support at least 9 and 10. You can goto modern.ie and signup for 3 months free of browserstack to test in various browsers.

IE 9: issues (may just be image sizing issue in header causing overlap with results)
IE 10: issues (same)
IE 11: looks good on desktop

![dashboard](https://f.cloud.github.com/assets/792287/1434118/b7089324-410d-11e3-8dc7-5b0fec96c9a4.png)

![dashboard-2](https://f.cloud.github.com/assets/792287/1434124/edf65f92-410d-11e3-9867-2a68f887efdf.png)

**Comment by wbprice** [comment]
Yikes.  Guess what I'm working on tomorrow? @BretFisher

**Comment by wbprice** [comment]
@bschoenfeld how much of this is hosted on rackspace vs. github?

**Comment by qwo** [comment]
all the front end is on github. The client side uses ajax calls to the API which is hosted on rackspace.

So none of this is on rackspace, only the https://github.com/c4hrva/hrt-bus-api i thnk is on rackspace

**Comment by qwo** [comment]
I don't have most IE but I always add these headings on bootstrap for IE.

http://www.initializr.com/builder?print&boot-hero&jquerymin&h5bp-iecond&h5bp-chromeframe&h5bp-analytics&h5bp-favicon&h5bp-appletouchicons&modernizrrespond&izr-emptyscript&boot-css&boot-scripts

``` html


<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="css/bootstrap.min.css">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="css/main.css">

        <script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

```

**Comment by bschoenfeld** [comment]
Stanley is mostly correct. The API server is on Heroku. The database is on
rackspace. Processing HRTs feed also happens on rackspace.

**Comment by BretFisher** [comment]
that's some good info for documentation. maybe we use this repo's readme for an overview of the whole system, since it's likely the first repo ppl will see. More to discuss/do tonight :)

**Comment by bschoenfeld** [comment]
Yeah. Architecture documentation was never great. Now that I've completely switched all my SaaS platforms, its completely useless.

**Comment by qwo** [comment]
the 2.2 and 2.3 bugs were fixed by ben in https://github.com/c4hrva/hrt-bus-finder/commit/552c924f5fcb1a4f1a8322f663a136091b808fa0

I checked on 4.0 - 4.2 and haven't been able to reproduce the imgur bug so closing this for now 

As always test, test test,
