### ISSUE TITLE
Point-Of-Interests should be disabled

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#75]
The map has points like parks, churches, buildings, etc that are selectable.

Should they be disabled or do they serve a use? 
![screen shot 2013-10-26 at 5 09 46 pm](https://f.cloud.github.com/assets/3683993/1414423/c1103e9e-3e83-11e3-9eda-84392df2d9dd.png)

![screen shot 2013-10-26 at 5 09 09 pm](https://f.cloud.github.com/assets/3683993/1414421/b09711e6-3e83-11e3-8c5e-af0237f3462f.png)

**Comment by bschoenfeld** [comment]
I disabled everything I could on the maps. If you know how to do this, please let me know.
