### ISSUE TITLE
Rebranding?

### ISSUE THREAD

**Issue by wbprice** [Code4HR/hrt-bus-finder#76]
Considering HRT's position on the Bus Tracker, are we still allowed to use their logo and name on our app or do we need to debrand/rebrand?   @kmcurry @bschoenfeld

**Comment by kmcurry** [comment]
It's best if it does not appear to be an HRT product. Mainly that has to do
with logos and colors. I'd rather not change the URLs and "HRT Bus Finder"
is perfectly accurate.

On Sun, Oct 27, 2013 at 11:07 AM, William Blaine Price <
notifications@github.com> wrote:

> Considering HRT's position on the Bus Tracker, are we still allowed to use
> their logo and name on our app or do we need to debrand/rebrand? @kmcurryhttps://github.com/kmcurry
> @bschoenfeld https://github.com/bschoenfeld
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/hrt-bus-finder/issues/76
> .

## 

Kevin Curry
Program Director
CfA Brigade
757.613.8158
GMT-4 (EDT)
http://brigade.codeforamerica.org

_Apply for Fellowship: http://codeforamerica.org/apply_

**Comment by wbprice** [comment]
Gotcha.  The logo we're using in the header uses elements from the HRT logo (waving stripes), so that might be cutting it close.  I'd be comfortable replacing it with the graphic from the favicon or removing it altogether.
