### ISSUE TITLE
Stop Finder

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/hrt-bus-finder#82]
Implemented but needs style and then the link should be added to the panel.

Then needs local storage to save favorite stops.

**Comment by wbprice** [comment]
I'm on it.  How can I get to it now?

**Comment by bschoenfeld** [comment]
http://hrtb.us/#/findStops

**Comment by wbprice** [comment]
being addressed in #84, which has the stupidest name ever but fixes the problem.

**Comment by wbprice** [comment]
except for the local storage bit, but we'll have to work on that.
