### ISSUE TITLE
App doesn't load

### ISSUE THREAD

**Issue by qwo** [Code4HR/hrt-bus-finder#93]
## Bus App request doesn't return.

Chrome
Safari 
As of 10:11PM 
<img src="https://f.cloud.github.com/assets/3683993/1433997/912eabfc-4108-11e3-990f-7d227bc89d8c.jpg" height="400px" width="200px" />

**Comment by qwo** [comment]
App is returning again fixed?

@wbprice were you having difficulty with the app today?

**Comment by wbprice** [comment]
It's still not loading on my mobile (Android 4, Chrome) or my roommate's tablet (Nook, running Chrome).

**Comment by qwo** [comment]
iPhone5: Safari/Chrome A O K
iPhone3GS: Safari/Chrome A O K - But no Modal on chrome?

**Comment by bschoenfeld** [comment]
First person to get the Android SDK and reproduce this in the emulator gets
a prize.

**Comment by bschoenfeld** [comment]
The emulator isn't loading the main screen, but I'm having a lot of trouble debugging. Can someone bring their Android device tonight and allow me to use it for debugging?

**Comment by wbprice** [comment]
I'll bring my  phone tonight.

**Comment by bschoenfeld** [comment]
Just got a hold of a low end Samsung phone running 4.0.4 and I didn't have any major issues using the app.

**Comment by bschoenfeld** [comment]
Ok. I have a theory about this. When the Home View is loaded, it asks the browser for the users location. The getCurrentLocation method takes two callbacks: success and fail. If, for some reason, the browser doesn't call either of these methods - the app will get stuck on the loading screen. The getCurrentLocation method also takes some options that includes a timeout. Maybe we need to use the timeout to make sure the app gets loaded. When the user doesn't have geolocation or geolocation fails, we use a hardcoded location in Downtown Norfolk to load the app. We should also show a banner warning that tells the user geolocation failed, so they are seeing Downtown Norfolk instead of their actual location and they should use the stop finder to get the stop closest to their location.

https://github.com/c4hrva/hrt-bus-finder/blob/gh-pages/js/busfinder.js#L484
https://developer.mozilla.org/en-US/docs/Web/API/PositionOptions

**Comment by qwo** [comment]
Sound Theory,
whenever the infinite loading happens on my end, it never asks for my
geolocation points on any devices.

On Wed, Oct 30, 2013 at 9:42 AM, Ben Schoenfeld notifications@github.comwrote:

> Ok. I have a theory about this. When the Home View is loaded, it asks the
> browser for the users location. The getCurrentLocation method takes two
> callbacks: success and fail. If, for some reason, the browser doesn't call
> either of these methods - the app will get stuck on the loading screen. The
> getCurrentLocation method also takes some options that includes a timeout.
> Maybe we need to use the timeout to make sure the app gets loaded. When the
> user doesn't have geolocation or geolocation fails, we use a hardcoded
> location in Downtown Norfolk to load the app. We should also show a banner
> warning that tells the user geolocation failed, so they are seeing Downtown
> Norfolk instead of their actual location and they should use the stop
> finder to get the stop closest to their location.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/PositionOptions
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/hrt-bus-finder/issues/93#issuecomment-27389507
> .
> 
> ---
> 
> NOTE: This message was trained as non-spam. If this is wrong, please
> correct the training as soon as possible.
> Spamhttps://www.spamtrap.odu.edu/canit/b.php?i=03KHpGLs7&m=0b5a04c73d55&t=20131030&c=s
> Not spamhttps://www.spamtrap.odu.edu/canit/b.php?i=03KHpGLs7&m=0b5a04c73d55&t=20131030&c=n
> Forget previous votehttps://www.spamtrap.odu.edu/canit/b.php?i=03KHpGLs7&m=0b5a04c73d55&t=20131030&c=f

## 

Stanley Zheng
B.S. Computer Science Major
Old Dominion University 2014
Cell: (347)-399-3732

**Comment by rjh427** [comment]
I can verify the theory, we have the same issue on our tablet site (t.cycletrader.com). If the user does not interact with the geolocation prompt, a default page never loads and the spinner spins forever - we have a ticket in to fix it but haven't gotten to it yet.

**Comment by BretFisher** [comment]
@bschoenfeld btw the Android SDK has a great free emulator http://developer.android.com/tools/devices/emulator.html

**Comment by bschoenfeld** [comment]
@BretFisher yeah, I remember it being pretty great when I used it a couple year ago, but I downloaded it last night and found it to be horribly slow and not have any easy way of debugging javascript in the stock browser. Bad times.

**Comment by BretFisher** [comment]
FYI http://www.browserstack.com also has 25 variants of Android to test
with.

**Comment by qwo** [comment]
I'm guessing a lot of the traffic is mobile traffic. I'll test most mobile browsers on android/ios and knock that out tonight.  I'll report back my browserstack findings..

**Comment by qwo** [comment]
Galaxy S Android 2.2| doesn't load 
Galaxy S2 2.3 | doesn't load
Moto Droid 4 | 2.3 doesn't load 
Nexus 4 | 4.2  doesn't load
HTC Hero | 1.5 doesn't load 
The problem versions for android seem to be 2.2, 2.3 and 4.2 .. If anyone have native of these devices recommend testing

**Comment by bschoenfeld** [comment]
Just pushed #94. I hope that it fixes this. Can you try again?

**Comment by bschoenfeld** [comment]
Confirmed that #94 fixes this issue in the Android emulator. Still need to add a bootstrap alert telling the user that geolocation is unavailable. They may need to click the allow button when prompted by the browser or they need to use the stop finder to manually search for their location.

**Comment by qwo** [comment]
Agreed @bschoenfeld bootstrap alert sounds like a good idea.
4.2 issue is corrected.

2.2 & 2.3 After passing the Modal, the loading animations stop and the app stops responding.

**Comment by bschoenfeld** [comment]
Thanks for your help on this, @stanzheng. I reproduced the problem in the emulator and fixed it, but if you could also confirm, I would appreciate it.
